DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tweets;

CREATE TABLE users(
  fullname VARCHAR(50) NOT NULL,
  username VARCHAR(15) NOT NULL,
  email VARCHAR(20),
  password VARCHAR(256) NOT NULL,
  filename VARCHAR(64) NOT NULL,
  totaltweets INTEGER DEFAULT 0,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(username)
);

CREATE TABLE tweets(
  originalOwner VARCHAR(15) NOT NULL, /* The person who first tweeted this tweet */
  body VARCHAR(256) NOT NULL,
  tweetid VARCHAR(20) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  owner VARCHAR(15) NOT NULL,
  retweet BOOLEAN NOT NULL,
  likes INTEGER DEFAULT 0,
  PRIMARY KEY(tweetid),
  FOREIGN KEY (owner) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE likes(
  tweetid VARCHAR(20) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  owner VARCHAR(15) NOT NULL,
  PRIMARY KEY(owner, tweetid),
  FOREIGN KEY (owner) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (tweetid) REFERENCES tweets(tweetid) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE follow(
  user1 VARCHAR(15) NOT NULL,
  user2 VARCHAR(15) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user1, user2),
  FOREIGN KEY (user1) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user2) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);